### ISSUE TITLE
UI Problems

### ISSUE THREAD

**Issue by solariz** [ppipada/vscode-flexigpt#9]
HEy,

it might be because FlexiGPT is a bit older now, last update a year ago. So things might have changed in vscode. But I still like the simplicity of FlexiGPT and love to use it.

Issue is that the UI of the chat input is to large and there is no way to resize it. Guess that can be simple fixed by set a max-height.

![image](https://github.com/ppipada/vscode-flexigpt/assets/4168339/169ade9a-1978-4fd0-b5f5-73976abcad8b)

Thanks for eventually looking into it.

**Comment by ppipada** [comment]
Hi,

Thanks for the report. With Vanilla JS (I first worked with the language in this extension via ChatGPT only so I may be missing something obvious), resizing turned out to be surprisingly convulated when I looked at it. Max height, etc works, but I wanted to have resizing rather than just a max. A lot of other enhancements I wanted in the UI (e.g streaming and prompt building, etc) were difficult to achieve. 

I planned to migrate to a simple react app inside vscode sometime back, but ran into some bandwidth issues. 
Hopefully I will get to completing it sometime soon and with it, the max height and resize issues get resolved. 

A simple workaround that I use to sidestep the above annoyance is to type something (just a single character) in the text box and delete it immediately + esc.  It comes back to the base size after this. I know this is horrible, but again, hopefully I will solve it soon enough.

**Comment by ppipada** [comment]
@solariz I have pushed a update to FlexiGPT today. 1.14.0

- Added max height for the text area (and a few more things to make it consistent). 
- So expected behaviour is: as you start typing or telling more to gpts, your text box will grow upto a certain size and then stop growing. i.e max-height. But, still "resize" to original (i.e 1 row only) is not present. For that the above suggested workaround is still there i.e type a char -> delete ->esc
- FYI: new release also adds support for latest openai/claude/gemini/huggingface/llama.cpp changes.  

Hope this solves your issue.
